<?php

namespace MarafyBundle\Repository;

/**
 * Categorie_subRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_subRepository extends \Doctrine\ORM\EntityRepository
{
}
