<?php

namespace MarafyBundle\Repository;

/**
 * Model_subRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Model_subRepository extends \Doctrine\ORM\EntityRepository
{
}
